[tool.mypy]
files = "src/{{ cookiecutter.repo_name }}"
ignore_missing_imports = true
python_version = "^3.11"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]

[tool.pytest.ini_options]
testpaths = [
  "tests",
]

[tool.coverage.run]
source_pkgs = [
  "{{ cookiecutter.repo_name }}",
]

########################################################################################
# POETRY                                                                               #
########################################################################################
[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
authors = [
{% if cookiecutter.author_email is defined %}
{name = "{{ cookiecutter.author_name }}"},
{% else %}
{name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}"},
{% endif %}
]
description = "some useful functions for myself"
version = "0.0.0"

repository = "https://github.com/kuchedav/{{ cookiecutter.repo_name }}"

# README file(s) are used as the package description
readme = ["README.md", "LICENSE"]

# Keywords (translated to tags on the package index)
keywords = ["packaging", "poetry"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
# Compatible Python versions
python = "^3.11"
