[build-system]
build-bakend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]

[project]
authors = [
  {name = "<AUTHOR_NAME>"},
]
dependencies = [
  "pandas >= 1.4.0",
]
dynamic = ["version"]
name = "{{ cookiecutter.  repo_name }}"
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
  "sklearn>=1.21.0"
]

[tool.coverage.run]
source_pkgs = [
  "{{ cookiecutter.  repo_name }}",
]

[tool.mypy]
files = "src/{{ cookiecutter.  repo_name }}"
ignore_missing_imports = true
python_version = "3.8"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]

[tool.setuptools.package.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/{{ cookiecutter.  repo_name }}/_version.py"
version_scheme = "python-simplified-semver"
local_scheme = "dirty-tag"